import Head from "next/head";
import { Button } from "@/ui/button";
import Hero from "@/components/hero";
import Image from "next/image";
import Features from "@/components/features";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full bg-white">
        <Hero />
        <Features />
      </main>
    </>
  );
}
